[package]
name = "bedfragment_ds"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rayon = "1.6"
indicatif = "0.17"
rand = "0.8"
regex = "1.10"
num_cpus = "1.16"